apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: redis:alpine
            command: ["sh", "-c", "redis-cli --rdb /data/dump.rdb && gsutil cp /data/dump.rdb gs://bidflow-backups/"]  # Mock gsutil
          restartPolicy: OnFailure