apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "bidflow-app.fullname" . }}-backend-config
  labels:
    {{- include "bidflow-app.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 4567