replicas: 1
image:
  repository: gcr.io/velvety-pagoda-474218-r6/bidflow-ruby
  tag: "v0.1"
language: ruby  # ruby or go
env:
  RUBY_GC_HEAP_GROWTH_FACTOR: "1.1"  # From Transcript 1
  AB_VARIANT: "A"  # A/B for product experiments
  REDIS_TTL: 30
service:
  type: ClusterIP
  port: 4567
livenessProbe:
  httpGet:
    path: /live
    port: 4567
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /ready
    port: 4567
  initialDelaySeconds: 5
  periodSeconds: 5
# Go-specific overrides (for polyglot self-service)
go:
  gc: 100  # GOGC default
  debug: "gctrace=0"
# A/B experiment config (product teammate)
ab:
  variants:
    A:
      redisTtl: 30
    B:
      redisTtl: 120