name: CI/CD Pipeline for BidFlow App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GKE_PROJECT: velvety-pagoda-474218-r6
  GKE_CLUSTER: bidflow-autopilot
  GKE_ZONE: us-central1
  IMAGE: gcr.io/velvety-pagoda-474218-r6/bidflow-ruby  # Hardcoded for workflow env
jobs:
  build:
    runs-on: ubuntu-latest
    env:  # Job-level env—no expressions needed here now
      FULL_IMAGE: gcr.io/velvety-pagoda-474218-r6/bidflow-ruby  # Hardcoded to match IMAGE
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GKE_PROJECT }}
    - name: Configure Docker
      run: gcloud auth configure-docker
    - name: Build Docker image
      run: |
        cd app/ruby-bidder
        docker build -t '${{ env.FULL_IMAGE }}:${{ github.sha }}' .
        docker push '${{ env.FULL_IMAGE }}:${{ github.sha }}'
    - name: Run tests (health check)
      run: |
        cd app/ruby-bidder
        docker run -d -p 4567:4567 --name test-bidflow '${{ env.FULL_IMAGE }}:${{ github.sha }}'
        sleep 5
        curl -f http://localhost:4567/health || { echo "Health check failed"; docker rm -f test-bidflow; exit 1; }
        docker rm -f test-bidflow
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only on main pushes
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GKE_PROJECT }}
    - name: Get GKE credentials
      run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}
    - name: Setup Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.15.0
    - name: Create namespace if needed
      run: kubectl create namespace bidflow --dry-run=client -o yaml | kubectl apply -f -
    - name: Deploy with Helm
      run: |
        helm upgrade --install bidflow-app helm/ \
          --values helm/values.yaml \
          --set image.tag='${{ github.sha }}' \
          --namespace bidflow \
          --create-namespace
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/bidflow-app -n bidflow --timeout=300s
        kubectl get pods -n bidflow -l app.kubernetes.io/name=bidflow-app